@echo off
echo Starting MDway Web Server...
start "" cmd /c "npm run start:web"
echo Waiting for server to initialize...
timeout /t 2 /nobreak >nul
echo Opening MDway in default browser...
start http://localhost:8080/web/index.html
